name: whatever-test

services:
  ollama:
    image: ollama/ollama:latest
    networks:
      - whatever_network_test
    ports:
      - "11436:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 3

  whatever:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - NODE_ENV=test
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "3002:8080"
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - whatever_network_test

networks:
  whatever_network_test: