FROM base AS dev

ENV ENV=dev \
    PORT=8080 \
    DOCKER=true

WORKDIR /app/backend

# Ensure the data directory exists and is owned by the correct user
RUN mkdir -p /app/backend/data && chown -R $UID:$GID /app/backend/data

COPY backend /app/backend

CMD ["bash", "dev.sh"]
