name: whatever-dev

services:
  frontend:
    build:
      context: .
      target: build
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    ports:
      - "3000:5173"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./svelte.config.js:/app/svelte.config.js
      - ./vite.config.ts:/app/vite.config.ts
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.svelte-kit:/app/.svelte-kit

  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    env_file: ".env.dev"
    environment:
      - ENV=dev
      - WEBUI_AUTH=False
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./backend:/app/backend
      - data:/app/backend/data

volumes:
  data: {}
