name: whatever-test

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama-test
    volumes:
      - ollama-test:/root/.ollama
    networks:
      - whatever_network_test
    ports:
      - "11436:11434"  # Different port for test Ollama API
    restart: unless-stopped

  whatever:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
        NODE_ENV: test
    image: ghcr.io/whatever/whatever:${WEBUI_DOCKER_TAG-main}
    container_name: whatever-test
    environment:
      - NODE_ENV=test
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OLLAMA_BASE_URL=http://ollama-test:11434
    volumes:
      - whatever-test:/app/data
      - ./cypress:/app/cypress  # Mount cypress tests
    ports:
      - "3002:8080"
    depends_on:
      - ollama
    networks:
      - whatever_network_test
    restart: unless-stopped

  whatever-cypress:
    image: cypress/included:latest
    container_name: whatever-cypress-test
    working_dir: /app
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    depends_on:
      - whatever
    environment:
      - CYPRESS_BASE_URL=http://whatever-test:8080
      - DEBUG=cypress:*
    entrypoint: []
    command: >
      /bin/sh -c "
      npm install typescript@latest &&
      cypress run --config-file /app/cypress.config.ts --headless
      "
    networks:
      - whatever_network_test

volumes:
  ollama-test:
  whatever-test:
  whatever-backend-test:

networks:
  whatever_network_test:
    driver: bridge