name: whatever-test

services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    container_name: ollama-test
    volumes:
      - ollama-test:/root/.ollama
    networks:
      - whatever_network_test
    ports:
      - "11436:11434"  # Different port for test Ollama API
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 3

  whatever:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
        NODE_ENV: test
    image: ghcr.io/whatever/whatever:${WEBUI_DOCKER_TAG-main}
    container_name: whatever-test
    environment:
      - NODE_ENV=test
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-test-key}  # Add default value
      - OLLAMA_BASE_URL=http://ollama-test:11436  # Fix port
    volumes:
      - whatever-test:/app/data
      - ./cypress:/app/cypress  # Mount cypress tests
    ports:
      - "3002:8080"
    depends_on:
      ollama:
        condition: service_healthy  # Add health check
      backend:
        condition: service_started
    networks:
      - whatever_network_test
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatever-backend-test
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - HOST=0.0.0.0
      - PORT=8080
      - OLLAMA_BASE_URL=http://ollama-test:11434
    volumes:
      - whatever-backend-test:/app/data
    networks:
      - whatever_network_test
    depends_on:
      - ollama
    restart: unless-stopped
    entrypoint: ["/bin/bash"]
    command: ["/app/backend/start.sh"]

  whatever-cypress:
    image: cypress/included:latest
    container_name: whatever-cypress-test
    working_dir: /app
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.ts:/app/cypress.config.ts
      - ./package.json:/app/package.json
    environment:
      - CYPRESS_BASE_URL=http://whatever-test:3002
      - DEBUG=cypress:*
    entrypoint: []
    command: >
      /bin/sh -c "
      npm install cypress typescript@latest &&
      npm install &&
      cypress run --config-file /app/cypress.config.ts --headless
      "
    networks:
      - whatever_network_test
    depends_on:
      - whatever
      - backend

volumes:
  ollama-test:
  whatever-test:
  whatever-backend-test:

networks:
  whatever_network_test:
    driver: bridge